apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
