apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: pytorch-seelam
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/amlc-hw3/pytorch-mnist:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1"
                - "--savemodel=/model/mnist_model.pt"  # Ensure to include this
              volumeMounts:
                - name: model-volume
                  mountPath: "/model"
          volumes:
            - name: model-volume
              persistentVolumeClaim:
                claimName: model-pvc
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: gcr.io/amlc-hw3/pytorch-mnist:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/opt/pytorch-mnist/mnist.py"
                - "--epochs=1"
                - "--savemodel=/model/mnist_model.pt"  # Ensure to include this
              volumeMounts:
                - name: model-volume
                  mountPath: "/model"
          volumes:
            - name: model-volume
              persistentVolumeClaim:
                claimName: model-pvc
